-- 목적: MES Web Service 기본 스키마를 생성한다.
-- 기능: 인증/감사/수주/작업/재고/품질/설비 기본 테이블을 만든다.
-- 이유: 화면 CRUD 구현과 테스트를 위한 최소 기반을 확보하기 위함이다.
-- 유지보수: 상세 컬럼 확정 시 테이블 구조를 보완한다.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(50) NOT NULL UNIQUE,
  user_name VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  phone VARCHAR(50),
  email VARCHAR(200),
  login_fail_count INT NOT NULL DEFAULT 0,
  locked_at DATETIME NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_type VARCHAR(50) NOT NULL,
  user_id VARCHAR(50) NULL,
  result VARCHAR(20) NOT NULL,
  ip_hash VARCHAR(255) NULL,
  user_agent_hash VARCHAR(255) NULL,
  detail_hash TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roles (
  role_code VARCHAR(30) PRIMARY KEY,
  role_name VARCHAR(100) NOT NULL,
  role_desc VARCHAR(200),
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS permissions (
  perm_key VARCHAR(100) PRIMARY KEY,
  perm_label VARCHAR(200) NOT NULL,
  perm_group VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_code VARCHAR(30) NOT NULL,
  perm_key VARCHAR(100) NOT NULL,
  allowed TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (role_code, perm_key),
  CONSTRAINT fk_role_permissions_perm FOREIGN KEY (perm_key) REFERENCES permissions(perm_key),
  CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_code) REFERENCES roles(role_code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS partners (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  partner_code VARCHAR(50) NOT NULL UNIQUE,
  partner_name VARCHAR(200) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  item_code VARCHAR(50) NOT NULL UNIQUE,
  item_name VARCHAR(200) NOT NULL,
  category VARCHAR(100),
  item_type VARCHAR(100),
  unit VARCHAR(50),
  spec VARCHAR(200),
  unit_price DECIMAL(18,2),
  partner_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_items_partner FOREIGN KEY (partner_id) REFERENCES partners(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS factories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  factory_name VARCHAR(200) NOT NULL,
  region VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS warehouses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  factory_id BIGINT NOT NULL,
  warehouse_name VARCHAR(200) NOT NULL,
  location VARCHAR(200),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_warehouses_factory FOREIGN KEY (factory_id) REFERENCES factories(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(50) NOT NULL UNIQUE,
  order_date DATE NOT NULL,
  due_date DATE NULL,
  item_id BIGINT NOT NULL,
  order_qty INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'planned',
  partner_id BIGINT NULL,
  owner_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_orders_partner FOREIGN KEY (partner_id) REFERENCES partners(id),
  CONSTRAINT fk_orders_owner FOREIGN KEY (owner_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS work_orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  work_no VARCHAR(50) NOT NULL UNIQUE,
  order_id BIGINT NOT NULL,
  plan_start_date DATE NULL,
  plan_end_date DATE NULL,
  plan_qty INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'planned',
  owner_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_work_orders_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_work_orders_owner FOREIGN KEY (owner_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory_status (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  item_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  stock_qty INT NOT NULL DEFAULT 0,
  stock_type VARCHAR(20) NOT NULL DEFAULT 'normal',
  last_in_date DATE NULL,
  last_out_date DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS defect_types (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  parent_category VARCHAR(100),
  name VARCHAR(200) NOT NULL,
  remark VARCHAR(200),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS defects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  defect_date DATE NOT NULL,
  item_id BIGINT NOT NULL,
  process_id BIGINT NULL,
  equipment_id BIGINT NULL,
  defect_type_id BIGINT NULL,
  defect_qty INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_defects_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_defects_defect_type FOREIGN KEY (defect_type_id) REFERENCES defect_types(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS equipments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  equipment_code VARCHAR(50) NOT NULL UNIQUE,
  equipment_name VARCHAR(200) NOT NULL,
  equipment_type VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'idle',
  ip_address VARCHAR(50),
  port_number INT,
  com_port VARCHAR(50),
  baud_rate INT,
  polling_interval INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS equipment_status (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  equipment_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_equipment_status_equipment FOREIGN KEY (equipment_id) REFERENCES equipments(id)
) ENGINE=InnoDB;
